// <auto-generated />
using System;
using System.Collections;
using Fuel.Infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Fuel.Infrastructure.Migrations
{
    [DbContext(typeof(postgresContext))]
    partial class postgresContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Fuel.Infrastructure.Models.A", b =>
                {
                    b.Property<double?>("RegexpReplace")
                        .HasColumnName("regexp_replace")
                        .HasColumnType("double precision");

                    b.ToTable("a");
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.B", b =>
                {
                    b.Property<string>("RegexpReplace")
                        .HasColumnName("regexp_replace")
                        .HasColumnType("text");

                    b.ToTable("b");
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsDriverMaster", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'', '1', '', '100000', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DriverMobile")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("DriverId");

                    b.ToTable("DCS_DriverMaster");
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsDriverService", b =>
                {
                    b.Property<int>("DriverServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("DistanceTravelled")
                        .HasColumnType("double precision");

                    b.Property<int>("DriverVehicleId")
                        .HasColumnType("integer");

                    b.Property<double?>("DrivingTimeHours")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("RestTimeHours")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("RestingEndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("RestingStartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("VehicleEndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("VehicleStartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("WorkTimeHours")
                        .HasColumnType("double precision");

                    b.HasKey("DriverServiceId");

                    b.HasIndex("DriverVehicleId")
                        .HasName("fkIdx_171");

                    b.ToTable("DCS_DriverService");
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsDriverVehicle", b =>
                {
                    b.Property<int>("DriverVehicleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("DriverVehicleId");

                    b.HasIndex("DriverId")
                        .HasName("fkIdx_159");

                    b.HasIndex("VehicleId")
                        .HasName("fkIdx_156");

                    b.ToTable("DCS_DriverVehicle");
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsFuelInfo", b =>
                {
                    b.Property<int>("FuelInfoId")
                        .HasColumnType("integer");

                    b.Property<double?>("CurrentVolume")
                        .HasColumnType("double precision");

                    b.Property<int>("DriverVehicleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PacketTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("RefuelVolume")
                        .HasColumnType("double precision");

                    b.HasKey("FuelInfoId");

                    b.HasIndex("DriverVehicleId")
                        .HasName("fkIdx_192");

                    b.ToTable("DCS_FuelInfo");
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("VehicleRealTimeInfoId")
                        .HasColumnType("integer");

                    b.HasKey("LocationId");

                    b.HasIndex("VehicleRealTimeInfoId");

                    b.ToTable("DCS_Location");
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsLogs", b =>
                {
                    b.Property<string>("Exception")
                        .HasColumnName("exception")
                        .HasColumnType("text");

                    b.Property<int?>("Level")
                        .HasColumnName("level")
                        .HasColumnType("integer");

                    b.Property<string>("LogEvent")
                        .HasColumnName("log_event")
                        .HasColumnType("jsonb");

                    b.Property<string>("Message")
                        .HasColumnName("message")
                        .HasColumnType("text");

                    b.Property<string>("MessageTemplate")
                        .HasColumnName("message_template")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.ToTable("dcs_logs");
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsLogs1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Application")
                        .HasColumnName("application")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Callsite")
                        .HasColumnName("callsite")
                        .HasColumnType("character varying(8000)")
                        .HasMaxLength(8000);

                    b.Property<string>("Exception")
                        .HasColumnName("exception")
                        .HasColumnType("character varying(8000)")
                        .HasMaxLength(8000);

                    b.Property<string>("Level")
                        .HasColumnName("level")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Logged")
                        .HasColumnName("logged")
                        .HasColumnType("text");

                    b.Property<string>("Logger")
                        .HasColumnName("logger")
                        .HasColumnType("character varying(8000)")
                        .HasMaxLength(8000);

                    b.Property<string>("Message")
                        .HasColumnName("message")
                        .HasColumnType("character varying(8000)")
                        .HasMaxLength(8000);

                    b.HasKey("Id");

                    b.ToTable("DCS_Logs");
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsVehicleMaster", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("TankCapacity")
                        .HasColumnType("double precision");

                    b.Property<string>("VehicleLicenseNo")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VehicleName")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("VehicleId");

                    b.ToTable("DCS_VehicleMaster");
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsVehicleRealTimeInfo", b =>
                {
                    b.Property<int>("VehicleRealTimeInfoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DriverVehicleId")
                        .HasColumnType("integer");

                    b.Property<int?>("HarshBreaking")
                        .HasColumnType("integer");

                    b.Property<int?>("HarshTurning")
                        .HasColumnType("integer");

                    b.Property<BitArray>("IgnitionStatus")
                        .HasColumnType("bit(1)");

                    b.Property<double?>("LoadVolume")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PacketTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("VehicleSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("VehicleRealTimeInfoId");

                    b.HasIndex("DriverVehicleId")
                        .HasName("fkIdx_184");

                    b.ToTable("DCS_VehicleRealTimeInfo");
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsDriverService", b =>
                {
                    b.HasOne("Fuel.Infrastructure.Models.DcsDriverVehicle", "DriverVehicle")
                        .WithMany("DcsDriverService")
                        .HasForeignKey("DriverVehicleId")
                        .HasConstraintName("FK_171")
                        .IsRequired();
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsDriverVehicle", b =>
                {
                    b.HasOne("Fuel.Infrastructure.Models.DcsDriverMaster", "Driver")
                        .WithMany("DcsDriverVehicle")
                        .HasForeignKey("DriverId")
                        .HasConstraintName("FK_159")
                        .IsRequired();

                    b.HasOne("Fuel.Infrastructure.Models.DcsVehicleMaster", "Vehicle")
                        .WithMany("DcsDriverVehicle")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("FK_156")
                        .IsRequired();
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsFuelInfo", b =>
                {
                    b.HasOne("Fuel.Infrastructure.Models.DcsDriverVehicle", "DriverVehicle")
                        .WithMany("DcsFuelInfo")
                        .HasForeignKey("DriverVehicleId")
                        .HasConstraintName("FK_192")
                        .IsRequired();
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsLocation", b =>
                {
                    b.HasOne("Fuel.Infrastructure.Models.DcsVehicleRealTimeInfo", "VehicleRealTimeInfo")
                        .WithMany("DcsLocation")
                        .HasForeignKey("VehicleRealTimeInfoId")
                        .HasConstraintName("FK_191")
                        .IsRequired();
                });

            modelBuilder.Entity("Fuel.Infrastructure.Models.DcsVehicleRealTimeInfo", b =>
                {
                    b.HasOne("Fuel.Infrastructure.Models.DcsDriverVehicle", "DriverVehicle")
                        .WithMany("DcsVehicleRealTimeInfo")
                        .HasForeignKey("DriverVehicleId")
                        .HasConstraintName("FK_184")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
